<?php

namespace AppBundle\Repository;

/**
 * GameProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameProjectRepository extends \Doctrine\ORM\EntityRepository
{
}
