<?php

namespace AppBundle\Repository;

/**
 * ResTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
