<?php

namespace AppBundle\Repository;

/**
 * TextureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextureRepository extends \Doctrine\ORM\EntityRepository
{
}
